### ISSUE TITLE
Merge GameController, GameManager and GameHUD?

### ISSUE THREAD

**Issue by HuangJunye** [HuangJunye/QPong-Unity#38]
We have separate scripts of GameController, GameManager and GameHUD. Is it a good idea to merge them? I keep forgetting which one does what function.

**Comment by boland25** [comment]
yes I think that there is probably some value there.  or at least changing the names of some of them  if merging is not possible.  @filemaster is out for a few days so I can take this one

**Comment by filemaster** [comment]
I split GameManager in that three files because each one has a different purpose:
* GameController is not destroyed and it was designed to control the scene changes, music (if we are going to add it) and all share varibles between scenes
* GameManager contain the logic of the game
* GameHUD is used to show scores and other info (text) in the screen

In my opinion it is better keep these files as they are.
